### ISSUE TITLE
Type error on line 453 of generate-tests-utils.xsl

### ISSUE THREAD

**Issue by cirulls** [xspec/xspec#23]
@AirQuick wrote in https://github.com/expath/xspec/issues/86 :

test.xsd (defines bar's type)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="x-urn:test" xmlns="x-urn:test"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="foo">
		<xs:complexType>
			<xs:attribute name="bar" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>
```
test.xml (an instance of test.xsd)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<foo bar="true" xmlns="x-urn:test" />
```
test.xsl (loads test.xml with or without validation)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="2.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<xsl:import-schema schema-location="test.xsd" />

	<xsl:variable name="foo-strict">
		<xsl:copy-of select="doc('test.xml')" validation="strict" />
	</xsl:variable>

	<xsl:variable name="foo-strip">
		<xsl:copy-of select="doc('test.xml')" validation="strip" />
	</xsl:variable>
</xsl:stylesheet>
```
test.xspec (tests test.xsl)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description stylesheet="test.xsl" xmlns:x="http://www.jenitennison.com/xslt/xspec"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<x:scenario label="Test-1">
		<x:call function="exactly-one">
			<x:param select="$foo-strict" />
		</x:call>
		<x:expect label="Result-1" select="$foo-strip" />
	</x:scenario>

	<x:scenario label="Test-2">
		<x:call function="exactly-one">
			<x:param select="$foo-strip" />
		</x:call>
		<x:expect label="Result-2" select="$foo-strict" />
	</x:scenario>
</x:description>
```
With those files and a schema-aware processor, XSpec fails:
```bash
C:\test>c:\xspec\bin\xspec.bat test.xspec
Creating XSpec Directory at "C:\test\xspec" ...

Creating Test Stylesheet...
"C:\test\xspec\test.xsl"
test.xspec

Running Tests...
Testing with SAXON EE 9.7.0.14
Test-1
Result-1
Test-2
Result-2
Type error on line 453 of generate-tests-utils.xsl:
  XPTY0004: Cannot compare xs:boolean to xs:string
Cannot compare xs:boolean to xs:string
```
Tested on the latest master branch clone.

**Comment by bar** [comment]
@cirulls what? please don;t use my handle to document your code :) thanks

**Comment by cirulls** [comment]
Sorry @bar, I copied the code verbatim and didn't realise that GitHub automatically translated it into a handle (the @ sign followed by a name indicates the name of an attribute in XML).  I have fixed this in this issue, sorry for the misunderstanding.

**Comment by cirulls** [comment]
@AirQuick, thanks for submitting this, I confirm it is a bug. I fixed in #24 and merged into master - note that this is in the [xspec repo within the xspec organisation](https://github.com/xspec/xspec) as I don't have write access to the expath organisation. 

I tested it by using the shell script and Saxon EE 9.6.0.4. Could you confirm it is working with your version of Saxon under Windows?

Thanks,

Sandro

**Comment by AirQuick** [comment]
Thank you for the fix. I'm going to test it.

Looks like you removed a "DO NOT... REMOVE" part: https://github.com/xspec/xspec/commit/86e9bbf676d027e14234338224977dc75b65d6b1#diff-e684b53ab134d1f4e4fd9d154fddbbdaL92 Is that ok?

**Comment by cirulls** [comment]
Thanks for spotting it, I just reinstate that part of the comments for now. I think at some point I'd like to consolidate all the copyright and license notes in one single file so that the code looks cleaner.

**Comment by AirQuick** [comment]
Verified that the original problem no longer reproduced on Windows + Java 1.8 u111 x64 + Saxon 9.7.0.14-EE. Thanks! However,

>  Only if this condition returns false, the second condition  $node1 = '...'  is evaluated

So when the condition returns false, the same error may still happen. For example,

**test.xsd** (defines boolean attribute `bar=false` by default):
```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="x-urn:test" xmlns="x-urn:test"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="foo">
		<xs:complexType>
			<xs:attribute default="false" name="bar" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>
```
**context.xml** (has `bar=true`):
```
<?xml version="1.0" encoding="UTF-8"?>
<foo bar="true" xmlns="x-urn:test" />
```
**expect.xml** (has `bar=false`, but I'm lazy enough to omit the default value):
```
<?xml version="1.0" encoding="UTF-8"?>
<foo xmlns="x-urn:test" />
```
**test.xsl** (has a template to return the context as is. Also complements the default values in **expect.xml** at runtime on behalf of lazy me):
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet exclude-result-prefixes="#all" version="2.0"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

	<xsl:import-schema schema-location="test.xsd" />

	<xsl:variable name="expect">
		<xsl:copy-of select="doc('expect.xml')" validation="strict" />
	</xsl:variable>

	<xsl:template match="/">
		<xsl:sequence select="." />
	</xsl:template>
</xsl:stylesheet>
```
**test.xspec** (just compares **context.xml** and **expect.xml**):
```
<?xml version="1.0" encoding="UTF-8"?>
<x:description stylesheet="test.xsl" xmlns:x="http://www.jenitennison.com/xslt/xspec"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<x:scenario label="Test">
		<x:context href="context.xml" />
		<x:expect label="Result" select="$expect" />
	</x:scenario>
</x:description>
```
In that case, I would expect XSpec to complete the test and report the result (of failure). But XSpec is terminated by the same error:
```
C:\test>c:\xspec\bin\xspec.bat test.xspec
Creating XSpec Directory at "C:\test\xspec" ...

Creating Test Stylesheet...
"C:\test\xspec\test.xsl"
test.xspec

Running Tests...
Testing with SAXON EE 9.7.0.14
Test
Result
Type error on line 453 of generate-tests-utils.xsl:
  XPTY0004: Cannot compare xs:boolean to xs:string
Cannot compare xs:boolean to xs:string
```

**Comment by cirulls** [comment]
That's a very good point! I think I've been lazy with my lazy evaluation (no pun intended!) and didn't check the scenario of a genuine failing test. I think I fixed this in #27 (see the pull request for technical notes) and tested it with both examples you provided. Could you confirm it works at your end and you're happy with this fix?

Thanks,

Sandro

**Comment by AirQuick** [comment]
Thanks, @cirulls. Verified the fix with the cases reported by me. On Windows 8.1 + Java 1.8 u111 x64 + Saxon 9.7.0.14-EE.

**Comment by cirulls** [comment]
Cool, thanks for confirming. Unfortunately I can't write a test for this as a non-open source version of Saxon would be needed to run the test suite via Travis. I'll investigate if it's possible to find a workaround, it'd be good to use your examples and get this issue covered by a test.

I'll close the issue for now, thanks for flagging it and helping with the solution.
